# Generated by Django 5.0 on 2024-12-28 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_configurationcite_alter_customuser_bloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationcite',
            name='nombre_blocs',
            field=models.IntegerField(default=1, help_text='Nombre total de blocs dans la cité', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bloc',
            field=models.CharField(blank=True, choices=[], help_text='Numéro du bloc', max_length=10),
        ),
    ]
